# Generated by Django 5.2.1 on 2025-06-06 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.AddField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 6, 6, 22, 32, 45, 514918, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="email",
            field=models.EmailField(
                default=datetime.datetime(
                    2025, 6, 6, 22, 33, 19, 318816, tzinfo=datetime.timezone.utc
                ),
                max_length=254,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="name",
            field=models.CharField(
                default=datetime.datetime(
                    2025, 6, 6, 22, 35, 57, 218102, tzinfo=datetime.timezone.utc
                ),
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
