services:
  - type: web
    name: shopping-platform
    env: python
    buildCommand: ""
    startCommand: gunicorn shopping_platform.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: shopping_platform.settings
      - key: SECRET_KEY
        value: votre_clé_secrète_django
      - key: DEBUG
        value: False
