services:
  - type: web
    name: shopping-platform
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn shopping_platform.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: shopping_platform.settings
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: 'False'
