services:
  - type: web
    name: shopping-platform
    env: python

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: bash ./start.sh  # ✅ utilise bash (pas ./start.sh seul)

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: shopping_platform.settings
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: 'False'
      - key: DATABASE_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: ALLOWED_HOSTS
        value: shopping-platform.onrender.com
      - key: PORT
        value: '8000'

      # Optionnel : pour créer automatiquement un superuser
      - key: CREATE_SUPERUSER
        value: 'true'
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false



