services:
  - type: web
    name: shopping-platform
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: shopping_platform.settings
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: 'False'
      - key: DATABASE_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: ALLOWED_HOSTS
        value: shopping-platform.onrender.com
      - key: PORT
        value: '8000'

