services:
  - type: web
    name: shopping-platform-v1
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn shopping_platform.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: shopping_platform.settings
      - key: "django-insecure-4f)hpxp_+ck7an-^^g*8ji$(fh38&^ddc7h@80l$iv3@rwa78!"
        value: your_django_secret_key
      - key: DEBUG
        value: False
